### PR TITLE
added /last wsapi method

### PR DESCRIPTION
**Pull request by kparlante**
@shane-tomlinson:

Implements /wsapi/interaction_data/last using limit:1 and descending:true, instead of grabbing all of the results and looking at the last one (https://github.com/mozilla/kpiggybank/pull/18)

assumes uuids are not generated randomly, as set in default.ini or local.ini:
[uuids]
algorithm = sequential

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@kparlante - this is great. When I get some breathing room, I'll test this and merge with the PR from mozilla/browserid#3195. Thank you so much!

**Comment by shane-tomlinson** [comment]
@kparlante - breathing room is hopefully early next week.

**Comment by shane-tomlinson** [comment]
@kparlante - I tried to spin up an ephemeral instance with this change today and am seeing errors:

```
npm http 200 https://registry.npmjs.org/sigmund/-/sigmund-1.0.0.tgz

npm ERR! Error: ENOENT, lstat '/tmp/deploy11345-5850-gguj8m/node_modules/jade/node_modules/transformers/node_modules/css/node_modules/css-stringify/Readme.md'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!
npm ERR! System Linux 3.2.30-49.59.amzn1.x86_64
npm ERR! command "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! cwd /tmp/deploy11345-5850-gguj8m
npm ERR! node -v v0.6.17
npm ERR! npm -v 1.1.21
npm ERR! path /tmp/deploy11345-5850-gguj8m/node_modules/jade/node_modules/transformers/node_modules/css/node_modules/css-stringify/Readme.md
npm ERR! fstream_path /tmp/deploy11345-5850-gguj8m/node_modules/jade/node_modules/transformers/node_modules/css/node_modules/css-stringify/Readme.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! message ENOENT, lstat '/tmp/deploy11345-5850-gguj8m/node_modules/jade/node_modules/transformers/node_modules/css/node_modules/css-stringify/Readme.md'
npm ERR! errno {}
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26)
```

Is the ami out of date or including the wrong version of node?

**Comment by kparlante** [comment]
I succeeded spinning up an ephemeral instance. Poking around, it looks like your kpiggybank repo is forked from jed/kpiggybank instead of mozilla/kpiggybank, and your package.json has awsbox at `*`, so I'm guessing you're pulling the latest awsbox. (There was some chatter in irc about node issues). Try pulling changes from mozilla/piggybank, which should be pegged to `"awsbox": "0.4.2"`

**Comment by kparlante** [comment]
@shane-tomlinson: that last comment was for you of course!

**Comment by shane-tomlinson** [comment]
@kparlante - you are right, my awsbox was out of date. After blowing away my node modules and re-installing, all good!

**Pull request merged**
